### PR TITLE
Feature/driver

### PR DESCRIPTION
**Pull request by guacke**
CI driver with support for specification of xyz file, basis set, molecular charge and (optional) printing of first- and second-order density matrices.

### CODE REVIEW

**Comment by guacke** [comment]
The Travis build fails, because the Boost libraries cannot be found. @lelemmen do you know a quick fix?

**Comment by lelemmen** [comment]
Apparently, it's not that strange of an issue. All our other libraries only use the header only part of Boost, which is correctly installed in the travis script. I the fix for this issue consists in compiling the boost libraries in Travis.

**Comment by lelemmen** [comment]
@guacke Do you think I cached the Boost compilation correctly? Could you take a look at the error at line 450 in the Travis log?

**Comment by lelemmen** [comment]
Rebase with the current develop is done.

**Comment by lelemmen** [comment]
@guacke The program options are really beautiful: nice work.

**Pull request merged**
